
CREATE TABLE CAPITOLE.PRICE
(
    ID         BIGINT NOT NULL,
    BRAND_ID   BIGINT,
    START_DATE TIMESTAMP,
    END_DATE   TIMESTAMP,
    PRICE_LIST BIGINT,
    PRODUCT_ID BIGINT,
    PRIORITY   BIGINT,
    PRICE      DECIMAL(4, 2),
    CURRENCY       VARCHAR(5)
)